// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./../src/components/base/Button.vue')['default']
    DragBox: typeof import('./../src/components/DragBox.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    IconFavicon: typeof import('./../src/components/icon/favicon.svg?component')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
