name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    paths:
      - 'src/**'
      - 'cypress/**'
      - 'pnpm-lock.yaml'
      - '*.json'
      - '*.yml'
      - '*.js'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Cache Cypress binary
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
          key: cypress-cache-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          build: pnpm run build
          start: pnpm run preview --port 3000
          config: baseUrl=http://localhost:3000
          browser: chrome
          record: false

      - name: Run Unit tests
        uses: cypress-io/github-action@v5
        with:
          install: false
          component: true
  build:
    runs-on: ${{ matrix.os }}
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    strategy:
      matrix:
        node_version: [16.x]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build --base="/${{ github.event.repository.name }}/"

      - name: Link 404.html to index.html (for GitHub Pages)
        run: |
          cd dist
          ln -s index.html 404.html

      - name: Deploy to GitHub Pages  
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
  release:
    name: release
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: VTBox